<thead>
  <tr>
    <th>No</th>
    <th>Mesin</th>
    <th>Kartu Proses</th>
    <th>Kain</th>
    <th>Warna</th>
    <th>Kode Warna</th>
    <th>KG</th>
    <th>Tanggal dan Waktu</th>
    <th>Status</th>
  </tr>
</thead>
<tbody>
  <tr>
    <th>1</th>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
  </tr>
  <tr>
    <th>1</th>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
  </tr>
  <tr>
    <th>1</th>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
  </tr>
  <tr>
    <th>1</th>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
  </tr>
  <tr>
    <th>1</th>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
    <td>@mdo</td>
    <td>Mark</td>
    <td>Otto</td>
  </tr>
</tbody>